### PR TITLE
Included Fx for multiple databases

### PR DESCRIPTION
**Pull request by nathannaveen**
Including https://github.com/uber-go/fx so that we can use multiple different databases in the future.

## Summary by CodeRabbit

- **New Features**
  - Introduced flexible storage management across various commands by allowing for dependency injection of storage instances.
  - Enhanced modularity and configurability of commands in the application, enabling them to utilize a shared storage mechanism.

- **Bug Fixes**
  - Improved unit testing reliability by replacing real storage instances with mocked versions.

- **Chores**
  - Updated project dependencies to enhance capabilities related to dependency injection, error handling, and logging.

- **Documentation**
  - Added a new `fxmodule.go` for integrating Redis storage within the Uber FX application framework.

- **Refactor**
  - Streamlined the application initialization and error handling logic using the FX framework.

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@

> ## Walkthrough
> The recent changes greatly enhance the modularity and testability of the codebase by introducing dependency injection for storage components across various command packages. By modifying constructors and methods to accept `pkg.Storage` as a parameter, the design promotes better encapsulation and flexibility. Additionally, the updates improve error handling and integrate new dependencies, collectively streamlining the application's architecture and enhancing maintainability.
> 
> ## Changes
> File(s)	Change Summary
> cmd/cache/cache.go	Updated `options` struct to include `storage`, enhancing encapsulation and flexibility.
> cmd/ingest/ingest.go	Modified `New` function to require `storage`, improving command initialization.
> cmd/ingest/osv/osv.go	Added `storage` field to `options`, allowing better management of storage instances.
> cmd/ingest/sbom/sbom.go	Replaced hardcoded storage retrieval with `storage` from `options`, promoting dependency injection.
> cmd/leaderboard/allKeys/keys.go	Integrated `storage` into `options` and `Run` method for increased flexibility.
> cmd/leaderboard/custom/custom.go	Updated `Run` to utilize `storage` from `options`, enhancing modularity.
> cmd/leaderboard/leaderboard.go	Modified `New` to accept `storage`, linking command initialization with the storage layer.
> cmd/leaderboard/weightedNACD/weightedNACD.go	Used `storage` in `Run` method, promoting better dependency management.
> cmd/query/query.go	Added `storage` to `options`, streamlining storage management.
> cmd/root/root.go	Updated `New` to require `storage`, improving command structure integration.
> go.mod	Added new dependencies for enhanced functionalities, including logging and error handling.
> main.go	Refactored main function to utilize Uber FX for improved dependency management.
> pkg/fxmodule.go	Introduced `NewRedisStorageModule` for easier Redis integration within the FX framework.
> pkg/parser_test.go	Shifted to using `NewMockStorage` for testing, enhancing reliability and clarity.
> pkg/redis_storage.go	Changed return type of `NewRedisStorage` to `Storage`, promoting interface-based design.
> pkg/storage.go	Removed singleton logic, enabling more flexible storage instance management.
> ## Sequence Diagram(s)
> ```mermaid
> sequenceDiagram
>     participant User
>     participant App as Application
>     participant Cmd as Command
>     participant Storage as Storage Instance
> 
>     User->>App: Initialize Application
>     App->>Storage: Create Storage Instance
>     App->>Cmd: Call New(storage)
>     Cmd->>Storage: Use Storage for Operations
>     Cmd->>User: Return Command Results
> ```
> > 🐰 "In the realm of code, we leap and bound,
> > With storage so flexible, joy can be found.
> > Dependency injection, a magical trick,
> > Makes testing and changes both easy and quick.
> > So hop on this journey, let’s celebrate cheers,
> > For a more modular codebase, we’ll conquer our fears!" 🐇
> 
> Thank you for using CodeRabbit. We offer it for free to the OSS community and would appreciate your support in helping us grow. If you find it useful, would you consider giving us a shout-out on your favorite social media?
> 
> Share
> Tips
> ### Chat
> There are 3 ways to chat with [CodeRabbit](https://coderabbit.ai):
> 
> * Review comments: Directly reply to a review comment made by CodeRabbit. Example:
>   
>   * `I pushed a fix in commit <commit_id>.`
>   * `Generate unit testing code for this file.`
>   * `Open a follow-up GitHub issue for this discussion.`
> * Files and specific lines of code (under the "Files changed" tab): Tag `@coderabbitai` in a new review comment at the desired location with your query. Examples:
>   
>   * `@coderabbitai generate unit testing code for this file.`
>   * `@coderabbitai modularize this function.`
> * PR comments: Tag `@coderabbitai` in a new PR comment to ask questions about the PR branch. For the best results, please provide a very specific query, as very limited context is provided in this mode. Examples:
>   
>   * `@coderabbitai generate interesting stats about this repository and render them as a table.`
>   * `@coderabbitai show all the console.log statements in this repository.`
>   * `@coderabbitai read src/utils.ts and generate unit testing code.`
>   * `@coderabbitai read the files in the src/scheduler package and generate a class diagram using mermaid and a README in the markdown format.`
>   * `@coderabbitai help me debug CodeRabbit configuration file.`
> 
> Note: Be mindful of the bot's finite context window. It's strongly recommended to break down tasks such as reading entire modules into smaller chunks. For a focused discussion, use review comments to chat about specific files and their changes, instead of using the PR comments.
> 
> ### CodeRabbit Commands (invoked as PR comments)
> * `@coderabbitai pause` to pause the reviews on a PR.
> * `@coderabbitai resume` to resume the paused reviews.
> * `@coderabbitai review` to trigger an incremental review. This is useful when automatic reviews are disabled for the repository.
> * `@coderabbitai full review` to do a full review from scratch and review all the files again.
> * `@coderabbitai summary` to regenerate the summary of the PR.
> * `@coderabbitai resolve` resolve all the CodeRabbit review comments.
> * `@coderabbitai configuration` to show the current CodeRabbit configuration for the repository.
> * `@coderabbitai help` to get help.
> 
> Additionally, you can add `@coderabbitai ignore` anywhere in the PR description to prevent this PR from being reviewed.
> 
> ### CodeRabbit Configuration File (`.coderabbit.yaml`)
> * You can programmatically configure CodeRabbit by adding a `.coderabbit.yaml` file to the root of your repository.
> * Please see the [configuration documentation](https://docs.coderabbit.ai/guides/configure-coderabbit) for more information.
> * If your editor has YAML language server enabled, you can add the path at the top of this file to enable auto-completion and validation: `# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json`
> 
> ### Documentation and Community
> * Visit our [Documentation](https://coderabbit.ai/docs) for detailed information on how to use CodeRabbit.
> * Join our [Discord Community](https://discord.com/invite/GsXnASn26c) to get help, request features, and share feedback.
> * Follow us on [X/Twitter](https://twitter.com/coderabbitai) for updates and announcements.

Can you create a PR with updates to docs on How FX is being used and why? With some diagrams?

**Comment by nathannaveen** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> @naveensrinivasan: Here's an outline for the documentation update on how the `fx` library is being used in the project and the benefits it brings:
> 
> ### How `fx` is Used
> The `fx` library from Uber is integrated into the project to manage dependencies and improve the modularity of the codebase. It allows for:
> 
> 1. **Dependency Injection**: `fx` facilitates dependency injection, which simplifies the management of dependencies across various components. This is achieved by defining modules that provide and consume dependencies.
> 2. **Lifecycle Management**: `fx` manages the lifecycle of applications, ensuring that resources are started and stopped in the correct order. This is particularly useful for managing database connections and other resources that require initialization and cleanup.
> 3. **Improved Encapsulation**: By injecting dependencies, components become more encapsulated and focused on their specific responsibilities, without needing to manage their dependencies directly.
> 4. **Testing and Flexibility**: With dependencies injected, components are easier to test in isolation. This also allows for greater flexibility in swapping out implementations for different environments or testing purposes.
> 
> ### Why `fx` is Used
> * **Scalability**: As the project grows, managing dependencies manually becomes cumbersome. `fx` provides a scalable solution to manage complex dependency graphs.
> * **Maintainability**: By using `fx`, the codebase becomes more maintainable, with clear separation of concerns and reduced coupling between components.
> * **Robustness**: The structured approach to dependency management reduces the likelihood of runtime errors due to missing or improperly configured dependencies.
> 
> ### Diagrams
> Here's a sequence diagram illustrating the use of `fx` in the application:
> 
> ```mermaid
> sequenceDiagram
>     participant User
>     participant App as Application
>     participant Cmd as Command
>     participant Storage as Storage Instance
> 
>     User->>App: Initialize Application
>     App->>Storage: Create Storage Instance
>     App->>Cmd: Call New(storage)
>     Cmd->>Storage: Use Storage for Operations
>     Cmd->>User: Return Command Results
> ```
> This diagram shows how the application initializes using `fx`, creates a storage instance, and injects it into commands, which then use the storage for their operations.
> 
> Would you like me to assist further in drafting the documentation or creating a PR with these updates?

Add why and how it is helpful?

**Comment by naveensrinivasan** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @naveensrinivasan: Here's an outline for the documentation update on how the `fx` library is being used in the project and the benefits it brings:
> 
> ### How `fx` is Used
> The `fx` library from Uber is integrated into the project to manage dependencies and improve the modularity of the codebase. It allows for:
> 
> 1. **Dependency Injection**: `fx` facilitates dependency injection, which simplifies the management of dependencies across various components. This is achieved by defining modules that provide and consume dependencies.
> 2. **Lifecycle Management**: `fx` manages the lifecycle of applications, ensuring that resources are started and stopped in the correct order. This is particularly useful for managing database connections and other resources that require initialization and cleanup.
> 3. **Improved Encapsulation**: By injecting dependencies, components become more encapsulated and focused on their specific responsibilities, without needing to manage their dependencies directly.
> 4. **Testing and Flexibility**: With dependencies injected, components are easier to test in isolation. This also allows for greater flexibility in swapping out implementations for different environments or testing purposes.
> 
> ### Why `fx` is Used
> * **Scalability**: As the project grows, managing dependencies manually becomes cumbersome. `fx` provides a scalable solution to manage complex dependency graphs.
> * **Maintainability**: By using `fx`, the codebase becomes more maintainable, with clear separation of concerns and reduced coupling between components.
> * **Robustness**: The structured approach to dependency management reduces the likelihood of runtime errors due to missing or improperly configured dependencies.
> 
> ### Diagrams
> Here's a sequence diagram illustrating the use of `fx` in the application:
> 
> ```mermaid
> sequenceDiagram
>     participant User
>     participant App as Application
>     participant Cmd as Command
>     participant Storage as Storage Instance
> 
>     User->>App: Initialize Application
>     App->>Storage: Create Storage Instance
>     App->>Cmd: Call New(storage)
>     Cmd->>Storage: Use Storage for Operations
>     Cmd->>User: Return Command Results
> ```
> This diagram shows how the application initializes using `fx`, creates a storage instance, and injects it into commands, which then use the storage for their operations.
> 
> Would you like me to assist further in drafting the documentation or creating a PR with these updates?
@coderabbitai
These docs aren't very helpful; they give a specific reason why it is useful with the Redis storage and how it can be extended to any other storage.

**Comment by naveensrinivasan** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @naveensrinivasan: Here's a more detailed explanation of how `fx` is useful with Redis storage and how it can be extended to other storage types:
> 
> ### How `fx` is Useful with Redis Storage
> 1. **Dependency Injection**: `fx` allows Redis storage to be injected as a dependency into various components of the application. This means that components do not need to know how to create or manage a Redis connection; they simply declare their need for a storage instance, and `fx` provides it.
> 2. **Lifecycle Management**: `fx` manages the lifecycle of the Redis connection. It ensures that the connection is established when the application starts and closed gracefully when the application shuts down. This reduces the risk of resource leaks and ensures that the connection is always in a valid state.
> 3. **Configuration Management**: By using `fx`, you can centralize the configuration of Redis (such as connection strings and options) in one place. This makes it easier to change configurations without affecting multiple parts of the codebase.
> 
> ### Extending to Other Storage Types
> * **Modular Design**: The same `fx` module that provides Redis can be adapted to provide other storage types. For example, you can create a module for a SQL database by changing the connection logic while keeping the dependency injection pattern intact.
> * **Interface-Based Design**: By defining a common `Storage` interface, different storage implementations (Redis, SQL, etc.) can be swapped easily. This allows the application to switch storage backends with minimal code changes.
> * **Testing Flexibility**: With `fx`, you can inject mock storage implementations during testing. This makes it easy to test components in isolation without needing a real database connection.
> 
> ### Example
> For Redis, you might have a module like this:
> 
> ```go
> func NewRedisStorageModule(addr string) fx.Option {
>     return fx.Provide(func() Storage {
>         return NewRedisStorage(addr)
>     })
> }
> ```
> 
> To extend this to another storage type, say SQL, you could create:
> 
> ```go
> func NewSQLStorageModule(dsn string) fx.Option {
>     return fx.Provide(func() Storage {
>         return NewSQLStorage(dsn)
>     })
> }
> ```
> 
> This approach allows you to maintain a consistent pattern for integrating different storage solutions, leveraging `fx` for dependency management and lifecycle control.
> 
> If you need further assistance or want to create a PR with these updates, feel free to ask!

@coderabbitai

Also a diagram will be helpful

**Comment by naveensrinivasan** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @naveensrinivasan: Here's a sequence diagram that illustrates how the `fx` library is used with Redis storage and how the same pattern can be extended to other storage types:
> 
> ```mermaid
> sequenceDiagram
>     participant App as Application
>     participant FX as FX Module
>     participant Redis as Redis Storage
>     participant SQL as SQL Storage
> 
>     App->>FX: Initialize with Redis Module
>     FX->>Redis: Provide Redis Storage
>     App->>Redis: Use Redis Storage
> 
>     App->>FX: Initialize with SQL Module
>     FX->>SQL: Provide SQL Storage
>     App->>SQL: Use SQL Storage
> ```
> This diagram shows how the application initializes using `fx`, which provides the necessary storage instance (Redis or SQL) based on the module used. The application then uses the provided storage for its operations. This pattern allows for easy swapping of storage backends by changing the module provided to `fx`.
> 
> If you need further assistance or want to create a PR with these updates, feel free to ask!

@coderabbitai

Combine the both and create a PR. Include how someone can extend this and reason for using it. Include the docs in the `docs` folder in the root.

Also include  why is Dependency Injection is helpful. 

Provide a link to FX also please in the docs.

**Comment by naveensrinivasan** [comment]
> Tip
> 
> For best results, initiate chat on the files or code changes.
> 
> @naveensrinivasan: Here's a draft for the documentation update on using the `fx` library, which you can include in the `docs` folder:
> 
> # Using the `fx` Library for Dependency Injection
> ## Overview
> The `fx` library from Uber is integrated into this project to manage dependencies and enhance the modularity of the codebase. This document outlines how `fx` is used with Redis storage and how the same pattern can be extended to other storage types.
> 
> ## Benefits of Dependency Injection
> * **Scalability**: Simplifies managing complex dependency graphs as the project grows.
> * **Maintainability**: Promotes a clear separation of concerns and reduces coupling between components.
> * **Testing Flexibility**: Allows for easy injection of mock implementations, facilitating isolated testing.
> * **Resource Management**: Ensures resources like database connections are properly initialized and cleaned up.
> 
> ## How `fx` is Used with Redis Storage
> 1. **Dependency Injection**: `fx` injects Redis storage as a dependency, allowing components to use it without managing its lifecycle.
> 2. **Lifecycle Management**: Manages the Redis connection lifecycle, ensuring proper initialization and cleanup.
> 3. **Configuration Management**: Centralizes Redis configuration, simplifying changes across the codebase.
> 
> ## Extending to Other Storage Types
> * **Modular Design**: Adapt the `fx` module to provide other storage types (e.g., SQL) by changing the connection logic.
> * **Interface-Based Design**: Use a common `Storage` interface to easily swap storage implementations.
> 
> ## Example
> For Redis:
> 
> ```go
> func NewRedisStorageModule(addr string) fx.Option {
>     return fx.Provide(func() Storage {
>         return NewRedisStorage(addr)
>     })
> }
> ```
> 
> For SQL:
> 
> ```go
> func NewSQLStorageModule(dsn string) fx.Option {
>     return fx.Provide(func() Storage {
>         return NewSQLStorage(dsn)
>     })
> }
> ```
> 
> ## Sequence Diagram
> ```mermaid
> sequenceDiagram
>     participant App as Application
>     participant FX as FX Module
>     participant Redis as Redis Storage
>     participant SQL as SQL Storage
> 
>     App->>FX: Initialize with Redis Module
>     FX->>Redis: Provide Redis Storage
>     App->>Redis: Use Redis Storage
> 
>     App->>FX: Initialize with SQL Module
>     FX->>SQL: Provide SQL Storage
>     App->>SQL: Use SQL Storage
> ```
> ## Additional Resources
> * [Uber FX GitHub Repository](https://github.com/uber-go/fx)
> 
> To create a PR with these updates, place this content in a new markdown file in the `docs` folder. If you need further assistance with the PR process, feel free to ask!

Great create PR for it please

**Comment by naveensrinivasan** [comment]
@coderabbitai Can you create unit tests for this PR?

**Review by naveensrinivasan — APPROVED** [review]

**Pull request merged**
